name: Ping Render Service

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10W minutes

jobs:
  ping_service:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the script
        run: |
          #!/bin/bash

          # Fetch the Render URL from GitHub Secrets
          RENDER_URL="https://level-super-mind.onrender.com"

          # Function to ping the service and log the result
          ping_service() {
            echo "$(date) - Sending request to $RENDER_URL"
            HTTP_RESPONSE=$(curl -I "$RENDER_URL" -s -o /dev/null -w "%{http_code}")

            if [ "$HTTP_RESPONSE" -eq 200 ]; then
              echo "$(date) - Successfully pinged $RENDER_URL, HTTP $HTTP_RESPONSE" >> ~/ping_log.txt
            else
              echo "$(date) - Failed to ping $RENDER_URL, HTTP $HTTP_RESPONSE" >> ~/ping_log.txt
            fi
          }